default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lgpd_development

test:
  <<: *default
  database: lgpd_test

production:
  <<: *default
  database: lgpd_production
  username: prc4
  password: <%= ENV['PRC4_DATABASE_PASSWORD'] %>
